// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1040","screenHeight":"624","changeWindowWidthTo":"1040","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"MBS_MobileDirPad","status":false,"description":"This script creates a DirPad and a action button for touch\ndevices in order to make the movement better.\n<MBS MobileDirPad>","parameters":{"DPad Image":"./img/mine/transparentDark07.png","ActionButton Image":"./img/mine/transparentDark34.png","CancelButton Image":"./img/mine/transparentDark35.png","Button Size":"52","DPad Position":"-90; -536","ActionButton Position":"912; 507","CancelButton Position":"976; 571","Opacity":"255","Hide Duration":"15","PC Debug":"true","Only in Map":"false"}}
];
